# Generated by Django 5.0.7 on 2024-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ag_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_make', models.CharField(max_length=100)),
                ('_model', models.CharField(max_length=100)),
                ('_price', models.FloatField()),
                ('_electric', models.BooleanField()),
            ],
        ),
    ]
