# Generated by Django 5.0.7 on 2024-08-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ag_table',
            old_name='_electric',
            new_name='electric',
        ),
        migrations.RenameField(
            model_name='ag_table',
            old_name='_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='ag_table',
            old_name='_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='ag_table',
            old_name='_price',
            new_name='price',
        ),
    ]
