# Generated by Django 5.0.7 on 2024-08-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_role',
            name='roleid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
