# Generated by Django 5.0.7 on 2024-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_history',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('threadid', models.IntegerField()),
                ('roleid', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_role',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tb_thread',
            fields=[
                ('threadid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
